- name: Uninstall Node Exporter and Remove SSH Public Key From Remote Server
  hosts: '{{ target }}'
  become: yes
  tasks:

    - name: Stop and disable Node Exporter service
      ansible.builtin.systemd:
        name: node_exporter
        state: stopped
        enabled: no

    - name: Remove Node Exporter systemd service file
      ansible.builtin.file:
        path: /etc/systemd/system/node_exporter.service
        state: absent

    - name: Remove Node Exporter binary
      ansible.builtin.file:
        path: /usr/local/bin/node_exporter
        state: absent

    - name: Remove Node Exporter user
      ansible.builtin.user:
        name: node_exporter
        state: absent
        remove: yes

    - name: Remove generated public SSH key from authorized_keys
      ansible.posix.authorized_key:
        user: root
        state: absent
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDK7cxzXoY353dhLdF9r319fC4Rvu+OoMpr65YpGh/jkF5R8em2tXifQJVPCDdnI5Iz+c+ClXiEKpXmAK0FEJRWepbCWTsH4OCt77kMjy/8jTZfGniDLCtfs1MNmn4CRXT9OJObC39PC59kEr1XA4uGuYzyzfyxTEDdB9yMHN7E8FRyxOusNaZHQhJWNIXmSIj+cltxPMkuU3etDPyd8e6LevyvwMReG5ZxJvsdkXQlftYwib3/MhT2WxQkn47VCtTfoRySxkUnebsT8jtpqFbrtrLIOFvdBW55MQIz6f0pxYyCcnrHSZ9G1tgd+x5yQflxJkRkfG9yndrgHU/861gStYkeKyQ1qHX++vGxPponrHAFESUn7fcT7n9yYD2xalMcK+BBLJswrZT4BZxBWGGQbbYQxRheIsxS2BJQU2nny1J5NJD/pMK/fMjIVrFMJW71yjbGyYQMsCxmPHHzCc0Z5UfOLOY3AbI4fRDKeklLqm5Orxpzjl924bcVqkNvOgJAAc9/7RGrXGQJuSfBz3HlYBVE/NSFkwX0Q8QRKUco8QZejoOiNIZRIPC7cCbOcW9iuhTrevYSQ0ay3fntbIGo5aJcYVhPXPK/7oz3k9o7r/JOxc0fDKIeBGDgWOB+Mc0FM4/pdD0cA9/SE4hBVaZkf4fQhOgl7YxfbihRmyybYQ== nodesforall"
        
