- name: Uninstall Node Exporter and Remove SSH Public Key From Remote Server
  hosts: {{ target }}
  become: yes
  tasks:

    - name: Stop and disable Node Exporter service
      ansible.builtin.systemd:
        name: node_exporter
        state: stopped
        enabled: no

    - name: Remove Node Exporter systemd service file
      ansible.builtin.file:
        path: /etc/systemd/system/node_exporter.service
        state: absent

    - name: Remove Node Exporter binary
      ansible.builtin.file:
        path: /usr/local/bin/node_exporter
        state: absent

    - name: Remove Node Exporter user
      ansible.builtin.user:
        name: node_exporter
        state: absent
        remove: yes

    - name: Remove generated public SSH key from authorized_keys
      ansible.posix.authorized_key:
        user: root
        state: absent
        key: "{{ ssh_keypair_result.public_key }}"
        
